listGames:
    handler: src/api/game/crud.list
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: GET
          path: /game
          integration: lambda

createGame:
    handler: src/api/game/crud.create
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: POST
          path: /game
          integration: lambda

getGameById:
    handler: src/api/game/crud.getById
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: GET
          path: /game/{gameId}
          integration: lambda

updateGameById:
    handler: src/api/game/crud.updateById
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: PATCH
          path: /game/{gameId}
          integration: lambda
  
deleteGameById:
    handler: src/api/game/crud.delete
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: DELETE
          path: /game/{gameId}
          integration: lambda
