
list<%= capitalizedModelName %>s:
    handler: src/api/<%= modelName %>/crud.listHandler
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: GET
          path: /<%= modelName %>

create<%= capitalizedModelName %>:
    handler: src/api/<%= modelName %>/crud.createHandler
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: POST
          path: /<%= modelName %>

get<%= capitalizedModelName %>ById:
    handler: src/api/<%= modelName %>/crud.getByIdHandler
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: GET
          path: /<%= modelName %>/{<%= modelName %>Id}

update<%= capitalizedModelName %>ById:
    handler: src/api/<%= modelName %>/crud.updateByIdHandler
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: PATCH
          path: /<%= modelName %>/{<%= modelName %>Id}
  
delete<%= capitalizedModelName %>ById:
    handler: src/api/<%= modelName %>/crud.deleteByIdHandler
    vpc: ${self:custom.vpc}
    events:
      - httpApi:
          method: DELETE
          path: /<%= modelName %>/{<%= modelName %>Id}
